//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Summaries.codeResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdministrationMenuStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdministrationMenuStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Summaries.codeResources.AdministrationMenuStrings", typeof(AdministrationMenuStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new class.
        /// </summary>
        internal static string AddNewClass {
            get {
                return ResourceManager.GetString("AddNewClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new user.
        /// </summary>
        internal static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Workspace.
        /// </summary>
        internal static string AddNewWorkspace {
            get {
                return ResourceManager.GetString("AddNewWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin?.
        /// </summary>
        internal static string AdminColumn {
            get {
                return ResourceManager.GetString("AdminColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete user &quot;{0}&quot; because it is protected against accidental deletion.
        /// </summary>
        internal static string CantDeleteUserDeletionProtected {
            get {
                return ResourceManager.GetString("CantDeleteUserDeletionProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Name.
        /// </summary>
        internal static string ClassName {
            get {
                return ResourceManager.GetString("ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &quot;{0}&quot; class?.
        /// </summary>
        internal static string ConfirmDeleteClass {
            get {
                return ResourceManager.GetString("ConfirmDeleteClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &quot;{0}&quot;?.
        /// </summary>
        internal static string ConfirmDeleteUser {
            get {
                return ResourceManager.GetString("ConfirmDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the workspace &quot;{0}&quot;?.
        /// </summary>
        internal static string ConfirmDeleteWorkspace {
            get {
                return ResourceManager.GetString("ConfirmDeleteWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Report.
        /// </summary>
        internal static string CreateWorkspaceReport {
            get {
                return ResourceManager.GetString("CreateWorkspaceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete class.
        /// </summary>
        internal static string DeleteClass {
            get {
                return ResourceManager.GetString("DeleteClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Class?.
        /// </summary>
        internal static string DeleteClassQuestion {
            get {
                return ResourceManager.GetString("DeleteClassQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user.
        /// </summary>
        internal static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User?.
        /// </summary>
        internal static string DeleteUserQuestion {
            get {
                return ResourceManager.GetString("DeleteUserQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Workspace.
        /// </summary>
        internal static string DeleteWorkspace {
            get {
                return ResourceManager.GetString("DeleteWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Workspace?.
        /// </summary>
        internal static string DeleteWorkspaceQuestion {
            get {
                return ResourceManager.GetString("DeleteWorkspaceQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit class.
        /// </summary>
        internal static string EditClass {
            get {
                return ResourceManager.GetString("EditClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        internal static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Workspace.
        /// </summary>
        internal static string EditWorkspace {
            get {
                return ResourceManager.GetString("EditWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flush Workspace.
        /// </summary>
        internal static string FlushWorkspace {
            get {
                return ResourceManager.GetString("FlushWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Name.
        /// </summary>
        internal static string LoginName {
            get {
                return ResourceManager.GetString("LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move User To....
        /// </summary>
        internal static string MoveUserTo {
            get {
                return ResourceManager.GetString("MoveUserTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Completed Successfully!.
        /// </summary>
        internal static string OperationCompleted {
            get {
                return ResourceManager.GetString("OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string RefreshBTN {
            get {
                return ResourceManager.GetString("RefreshBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total of Registered Users.
        /// </summary>
        internal static string TotalRegisteredUsers {
            get {
                return ResourceManager.GetString("TotalRegisteredUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion Protected?.
        /// </summary>
        internal static string UserDeletionProtectedColumn {
            get {
                return ResourceManager.GetString("UserDeletionProtectedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Summaries.
        /// </summary>
        internal static string WorksapceSavedSummaries {
            get {
                return ResourceManager.GetString("WorksapceSavedSummaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace.
        /// </summary>
        internal static string Workspace {
            get {
                return ResourceManager.GetString("Workspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string WorkspaceName {
            get {
                return ResourceManager.GetString("WorkspaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read?.
        /// </summary>
        internal static string WorkspaceReadColumn {
            get {
                return ResourceManager.GetString("WorkspaceReadColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write?.
        /// </summary>
        internal static string WorkspaceWriteColumn {
            get {
                return ResourceManager.GetString("WorkspaceWriteColumn", resourceCulture);
            }
        }
    }
}
